name = "No Flesh Within Chest"
author = "YoruNina"
version = "1.0.2-DIM"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f25d7a319fc4bff21177e530f136d8216dd6fb3ea3da0b6eb5340cfe844e767d"

[versions]
forge = "43.3.5"
minecraft = "1.19.2"
